name: wise_scalars
description: "A Flutter plugin to handle scalar types and their localizations."
version: 0.0.1
homepage: https://github.com/wisemen-digital/wisemen-flutter-packages/packages/wise_scalars
repository: https://github.com/wisemen-digital/wisemen-flutter-packages/packages/wise_scalars

environment:
  sdk: ^3.10.3
  flutter: '>=3.3.0'
resolution: workspace

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  intl: ^0.20.2
  meta: ^1.17.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.wise_scalars
        pluginClass: WiseScalarsPlugin
      ios:
        pluginClass: WiseScalarsPlugin
