name: wise_ultra_update
description: An ULTRA package that shows a dialog when an update is available
version: 1.0.1
homepage: https://github.com/wisemen-digital/wisemen-flutter-packages/packages/wise_ultra_update
repository: https://github.com/wisemen-digital/wisemen-flutter-packages/packages/wise_ultra_update

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.19.5'
resolution: workspace
dependencies:
  # Flutter
  flutter:
    sdk: flutter

  # Wisemen
  wisecore: '>=2.0.0 < 3.0.0'
  wise_theming: '>=1.0.0 <2.0.0'
  wisewidgetslibrary: '>=2.0.4 <3.0.0'

  # Riverpod
  riverpod_annotation: '>=3.0.0 <4.0.0'
  riverpod: ">=3.0.0 <4.0.0"
  hooks_riverpod: '>=3.0.0 <4.0.0'

  # Client
  wiseclient: '>=1.1.1 <2.0.0'

  # SVG
  flutter_svg: '>=2.1.0 <3.0.0'

  # Package info
  package_info_plus: '>=9.0.0 <10.0.0'

dev_dependencies:
  build_runner: ^2.4.15
  riverpod_generator: ^3.0.2
  json_serializable: ^6.9.4
  # Static analysis & linting
  lints: ^5.1.1
  mocktail: ^1.0.4

  # Testing
  test: ^1.25.15

  # Mocking
  mockito: ^5.4.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - test/assets/