name: wisemenflutterpackages
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - packages/wiseclient
  - packages/wisecore
  - packages/wisewidgetslibrary
  - packages/wise_nav_bar
  - packages/wise_zitadel_login
  - packages/wise_theming
  - packages/wise_ultra_update
dev_dependencies:
  melos: ^6.3.2
  coverage: ^1.11.1

flutter:
  assets:
    - assets/flutter_logo.png
