name: flutter_ultra_playground
description: A Wisemen Flutter project.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  # Flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Wisemen
  wise_theming: ^1.0.0
  wise_ultra_login:
    path: ../wisemen-flutter-packages/packages/wise_ultra_login
  wise_ultra_settings:
    path: ../wisemen-flutter-packages/packages/wise_ultra_settings
  wise_ultra_update:
    path: ../wisemen-flutter-packages/packages/wise_ultra_update
  wisewidgetslibrary: ^2.1.0
  wise_nav_bar: ^0.0.3
  
  # Networking
  wiseclient: ^1.1.1
  
 # Riverpod
  riverpod_annotation: ^3.0.2
  hooks_riverpod: ^3.0.2

  # Utils
  path_provider: ^2.1.5
  faker: ^2.2.0
  
  # Database
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.38
  
  # Device info
  package_info_plus: ^9.0.0

  # Splash
  flutter_native_splash: ^2.4.6

  # Icon
  icons_launcher: ^3.0.3

  # Logging
  talker_flutter: ^5.0.2

  # Onesignal
  onesignal_flutter: ^5.3.4

  # Sentry
  sentry_flutter: ^9.6.0

  path: any
  dio: any
  fresh_dio: any
  auto_route: any
  flutter_secure_storage: any
  shared_preferences: any
  flutter_riverpod: any

  # Auth
  flutter_appauth: ^9.0.0
  flutter_custom_tabs: ^2.4.0

  # SVG
  flutter_svg: ^2.2.1

  # Flutter sticky header
  flutter_sticky_header: ^0.8.0

  # App settings
  app_settings: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Code generation
  build_runner: ^2.5.4

  # Riverpod
  riverpod_generator: ^3.0.2

  # Routing
  auto_route_generator: ^10.2.3
  
  # Data
  json_serializable: ^6.9.5
  
  # Database
  drift_dev: ^2.27.0
  
  # Flavors
  flutter_flavorizr: ^2.4.1
  # Linters  
  riverpod_lint: ^3.0.2
  custom_lint: ^0.8.0

# flavors
flavorizr:
  flavors:
    # dev
    development:
      app:
        name: "Flutter Ultra"
      android:
        applicationId: "com.wisemen.app.development"
      ios:
        bundleId: "com.wisemen.app.development"
    # staging
    staging:
      app:
        name: "Flutter Ultra"
      android:
        applicationId: "com.wisemen.app.staging"
      ios:
        bundleId: "com.wisemen.app.staging"
    # test
    qa:
      app:
        name: "Flutter Ultra"
      android:
        applicationId: "com.wisemen.app.qa"
      ios:
        bundleId: "com.wisemen.app.qa"
    # production
    production:
      app:
        name: "Flutter Ultra"
      android:
        applicationId: "com.wisemen.app"
      ios:
        bundleId: "com.wisemen.app"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should comply with ISO-639-1 and ISO-3166-1 (e.g. "en", "en_GB"). Default: en
