name: wise_sentry
description: "A Wisemen wrapper for Sentry logging"
version: 0.0.1
homepage: https://github.com/wisemen-digital/wisemen-flutter-packages/packages/wise_sentry
repository: https://github.com/wisemen-digital/flutter-networking-client/packages/wise_sentry

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.19.5'

dependencies:
  flutter:
    sdk: flutter
  sentry_flutter: ^9.7.0
  dio: '>=5.0.0 <6.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

